dist: bionic
language: python
python:
  - "3.7"

before_install:
  - touch .env

install:
  - docker-compose build

before_script:
  - docker-compose up -d

script:
  - docker-compose exec server pytest /app/
  - docker-compose exec server mypy /app/

notifications:
  email: false

deploy:
  - provider: script
    script: bash scripts/travis_deploy_tags.sh
    on:
      tags: true
      all_branches: true
      repo: vote/turnout
  - provider: script
    script: bash scripts/travis_deploy_master.sh
    on:
      branch: master
      repo: vote/turnout
