dist: bionic
language: python
python:
  - "3.7"

cache:
  bundler: true
  directories:
    - $HOME/docker

before_install:
  - if [[ -d $HOME/docker ]]; then ls $HOME/docker/*.tar.gz | xargs -I {file} sh -c "zcat {file} | docker load"; fi
  - touch .env

install:
  - docker-compose build redis postgres server

script:
  - docker-compose run server bash -c "pytest /app/ && mypy /app/"

before_cache:
  # Save tagged docker images
  - >
    mkdir -p $HOME/docker && docker images -a --filter='reference=*turnout*' --filter='dangling=false' --format '{{.Repository}}:{{.Tag}} {{.ID}}'
    | xargs -n 2 -t sh -c 'test -e $HOME/docker/$1.tar.gz || docker save $0 | gzip -2 > $HOME/docker/$1.tar.gz'

notifications:
  email: false

deploy:
  - provider: script
    script: bash scripts/travis_deploy_tags.sh
    on:
      tags: true
      all_branches: true
      repo: vote/turnout
  - provider: script
    script: bash scripts/travis_deploy_master.sh
    on:
      branch: master
      repo: vote/turnout
