FROM python:3.7-buster
ENV APP_DIR=/app
WORKDIR $APP_DIR
COPY scripts/docker_build_step1.sh scripts/docker_build_step2.sh /root/
COPY app/requirements.txt app/package.json app/package-lock.json $APP_DIR/
RUN bash /root/docker_build_step1.sh
RUN apt-get update && apt-get install -y \
    wait-for-it && apt-get clean
