version: '3.7'
services:
  postgres:
    container_name: postgres_turnout
    image: postgis/postgis:11-2.5
    environment:
      - POSTGRES_DB=turnout
      - POSTGRES_PASSWORD=turnout
    ports:
      - "5432:5432"
    volumes:
      - pgdata_turnout:/var/lib/postgresql/data

  redis:
    container_name: redis_turnout
    image: 'redis:5.0.5'
    ports:
      - "127.0.0.1:6379:6379"
    volumes:
      - redisdata_turnout:/data

  server:
    build:
      context: .
      dockerfile: Dockerfile-dev
      cache_from:
        - voteamerica/turnout-ci-cache:latest
    image: voteamerica/turnout-ci-cache:latest
    entrypoint: wait-for-it postgres:5432 redis:6379 --
    command: watchmedo auto-restart --directory /app/ --patterns='*.py;*.yml;*.pdf' --recursive -- gunicorn -b 0.0.0.0:8000 -c /app/turnout/gunicorn_dev.conf.py turnout.wsgi
    volumes:
      - ./app:/app:cached
    ports:
      - "9001:8000"
    environment:
      - SECRET_KEY=abcd
      - DJANGO_SETTINGS_MODULE=turnout.settings
      - DATABASE_URL=postgis://postgres:turnout@postgres:5432/turnout
      - REDIS_URL=redis://redis:6379
      - ALLOWED_HOSTS=*
      - DEBUG=True
      - DD_AGENT_HOST=echo
      - DD_DOGSTATSD_PORT=3333
    env_file:
      - .env
    depends_on:
      - postgres
      - redis

  beat:
    image: voteamerica/turnout-ci-cache:latest
    entrypoint: wait-for-it postgres:5432 redis:6379 --
    command: watchmedo auto-restart --directory /app/ --pattern=*.py --recursive -- python -m celery -A turnout.celery_app beat --scheduler redbeat.RedBeatScheduler
    volumes:
      - ./app:/app
    environment:
      - SECRET_KEY=abcd
      - DJANGO_SETTINGS_MODULE=turnout.settings
      - DATABASE_URL=postgis://postgres:turnout@postgres:5432/turnout
      - REDIS_URL=redis://redis:6379
      - ALLOWED_HOSTS=*
      - DEBUG=True
      - DD_AGENT_HOST=echo
      - DD_DOGSTATSD_PORT=3333
    env_file:
      - .env
    depends_on:
      - postgres
      - redis

  worker:
    image: voteamerica/turnout-ci-cache:latest
    entrypoint: wait-for-it postgres:5432 redis:6379 --
    command: watchmedo auto-restart --directory /app/ --patterns='*.py;*.yml;*.pdf' --recursive -- python -m celery -A turnout.celery_app worker -Q default
    volumes:
      - ./app:/app
    environment:
      - SECRET_KEY=abcd
      - DJANGO_SETTINGS_MODULE=turnout.settings
      - DATABASE_URL=postgis://postgres:turnout@postgres:5432/turnout
      - REDIS_URL=redis://redis:6379
      - ALLOWED_HOSTS=*
      - DEBUG=True
      - DD_AGENT_HOST=echo
      - DD_DOGSTATSD_PORT=3333
    env_file:
      - .env
    depends_on:
      - postgres
      - redis
      - beat

  selenium:
    image: selenium/standalone-chrome:3.141.59-20200525
    ports:
      - "4444:4444"
    shm_size: '2gb'

  client:
    image: voteamerica/turnout-ci-cache:latest
    command: npm run develop
    volumes:
      - ./app:/app
      - /app/node_modules
    ports:
      - "35729:35729"
    env_file:
      - .env

  echo:
    image: voteamerica/turnout-ci-cache:latest
    command: python -m echo
    volumes:
      - ./app/echo.py:/app/echo.py
    ports:
      - "3333:3333"

  docs:
    build:
      context: .
      dockerfile: Dockerfile-docs
    command: mkdocs serve -a 0.0.0.0:8000
    volumes:
      - ./docs:/docs
    ports:
      - "9003:8000"

volumes:
  pgdata_turnout:
  redisdata_turnout:
