# Generated by Django 2.2.14 on 2020-07-15 19:04

import common.enums
import common.fields
from django.db import migrations, models
import django.db.models.deletion
import django_smalluuid.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proxy',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('proxy', models.TextField(primary_key=True, serialize=False)),
                ('description', models.TextField(null=True)),
                ('state', common.fields.TurnoutEnumField(enum=common.enums.ProxyStatus, null=True)),
                ('failure_count', models.IntegerField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('uuid', django_smalluuid.models.SmallUUIDField(default=django_smalluuid.models.UUIDDefault(), editable=False, primary_key=True, serialize=False, unique=True)),
                ('url', models.TextField(null=True)),
                ('description', models.TextField(null=True)),
                ('state_up', models.BooleanField(null=True)),
                ('state_changed_at', models.DateTimeField(null=True)),
                ('last_went_down_at', models.DateTimeField(null=True)),
                ('last_went_up_at', models.DateTimeField(null=True)),
                ('last_tweet_at', models.DateTimeField(null=True)),
                ('uptime_day', models.FloatField(null=True)),
                ('uptime_week', models.FloatField(null=True)),
                ('uptime_month', models.FloatField(null=True)),
                ('uptime_quarter', models.FloatField(null=True)),
            ],
            options={
                'ordering': ['-modified_at'],
            },
        ),
        migrations.CreateModel(
            name='SiteCheck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('state_up', models.BooleanField(null=True)),
                ('ignore', models.BooleanField(null=True)),
                ('load_time', models.FloatField(null=True)),
                ('error', models.TextField(null=True)),
                ('proxy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='leouptime.Proxy')),
                ('site', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='leouptime.Site')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
