site_name: VoteAmerica Developer Documentation
docs_dir: 'turnout'
nav:
    - Home: 'index.md'
    - 'API':
        - 'Election Information API': '/api/'
        - 'State Voter Tool Uptime API': '/api/leouptime/'
        - 'Action API': '/api/action/'
    - 'Tool Embed':
        - 'Embed Codes': '/embed/'
        - 'Form Prefilling': '/embed/prefill/'
        - 'Free Embed Code': '/embed/free/'
        - 'Events and Google Tag Manager': '/embed/gtm/'
        - 'Source Tracking': '/embed/tracking/'
        - 'WordPress': '/embed/wordpress/'
    - 'Tool Admin':
        - 'Introduction': '/admin/'
        - 'Export Format': '/admin/exportformat/'
    - 'Integrations':
        - 'ActionNetwork': '/integrations/actionnetwork/'
        - 'Bluelink': '/integrations/bluelink/'
        - 'The Movement Cooperative': '/integrations/tmc'
    - 'Open Source Development': '/opensource/'
collapse_navigation: false
theme:
  name: material
  logo: images/logo.png
  favicon: images/favicon.png
  palette:
    primary: red
    accent: black
  font:
    text: Open Sans
extra_css:
  - styles/extra.css
markdown_extensions:
  - admonition
  - codehilite
  - meta
  - attr_list
